name: Sync Git Repo

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        REPO_URL:
          - 'https://github.com/spencerwooo/onedrive-vercel-index.git'
          - 'https://github.com/2dust/v2rayN.git'
          - 'https://github.com/2dust/v2rayNG.git'
          - 'https://github.com/2dust/clashN.git'
          - 'https://github.com/v2ray/v2ray-core.git'
          - 'https://github.com/macronut/phantomsocks.git'
          - 'https://github.com/macronut/ghostcp.git'
          - 'https://github.com/macronut/godivert.git'
          - 'https://github.com/macronut/magisk-module-phantomsocks.git'
          - 'https://github.com/zizifn/edgetunnel.git'
          - 'https://github.com/Grasscutters/Grasscutter.git'
          - 'https://github.com/pandora-next/deploy.git'

    steps:
      - name: Clone git repository
        run: |
          git clone --mirror ${{ matrix.REPO_URL }}
          
      - name: Push to remote
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_USERMAIL: ${{ secrets.GITLAB_USERMAIL }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        run: |
          export REPO_NAME=$(basename "${{ matrix.REPO_URL }}" .git)
          
          cd $REPO_NAME.git
          git config user.name $GITLAB_USERNAME
          git config user.email $GITLAB_USERMAIL
          git remote add gitlab https://$GITLAB_USERNAME:$GITLAB_PASSWORD@gitlab.com/mirrors_git/$REPO_NAME.git
          git push gitlab --all
